version: "3.7"

services:
  app:
    build:
      context: .
    ports:
      - 8081:8080
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - LOGGING_CONGIF=classpath:log4j2-local.xml
      - CLIENT_OPA12ASSESS_MEANS_ADDRESS=http://host.docker.internal:8787/determinations-server/assess/soap/generic/12.2/MeansAssessment
      - CLIENT_OPA12ASSESS_BILLING_ADDRESS=http://host.docker.internal:8787/determinations-server/assess/soap/generic/12.2/BillingAssessment
      - CLIENT_OPA12ASSESS_SECURITY_USER_NAME=admin
      - CLIENT_OPA12ASSESS_SECURITY_USER_PASSWORD=Passw0rd
      - SERVER_OPA10ASSESS_PATH=/opadrulebase
      - SERVER_OPA10ASSESS_SECURITY_USER_NAME=admin
      - SERVER_OPA10ASSESS_SECURITY_USER_PASSWORD=Welcome123
      - CXF_PATH=/ccms/ws
      - CCMS_REF-DATA-FILE=reference/opa_entities.csv




